config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="landing-home"),
    path("privacy/", TemplateView.as_view(template_name="pages/privacy.html"), name="privacy"),
    path("contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"),
    path("people/", TemplateView.as_view(template_name="pages/people.html"), name="people"),
    path("civil-organizations/", TemplateView.as_view(template_name="pages/civil.html"), name="civil"),
    path("contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("findhelp.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("help/", include("findhelp.helpticket.urls", namespace="helpticket")),
    path('i18n/', include('django.conf.urls.i18n')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path('api/register/', include('rest_auth.registration.urls')),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

findhelp/helpticket/urls.py
from django.urls import path

from findhelp.helpticket import views


app_name = "helpticket"
urlpatterns = [
    path("listings/all", view=views.ticket_list_view, name='home'),
    path("listings/category/<pk>/", view=views.ticket_list_categorized_view, name='categorized'),
    path("create/", view=views.ticket_create_view, name='create-ticket'),
    path("my-listings/update/<pk>/", view=views.ticket_update_view, name='update-ticket'),
    path("my-listings/delete/<pk>/", view=views.ticket_delete_view, name='delete-ticket'),
    path("my-listings/", view=views.profile_ticket_list_view, name='profile')
    # path("tickets/", views.tickets_view, name='tickets'),
]

findhelp/users/urls.py
from django.urls import path

from findhelp.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

findhelp/helpticket/models.py
from django.db import models
from findhelp.users.models import User
from django.utils.translation import ugettext_lazy as _


class HelpCategory(models.Model):
    name = models.CharField(max_length=100, blank=False)
    description = models.TextField()

    def __str__(self):
        return str(self.name)


class HelpTicket(models.Model):
    categories = models.ManyToManyField(HelpCategory, verbose_name=_('Categories'), related_name="ticket_category")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="ticket_owner")
    city = models.CharField(verbose_name=_('City'), max_length=100)
    description = models.TextField(verbose_name=_('Description'), blank=False)
    contact = models.CharField(verbose_name=_('Contact'), max_length=150,)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        return str(self.owner.name) + ' :' + ' at ' + self.city

findhelp/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

findhelp/helpticket/forms.py
from django import forms

from findhelp.helpticket.models import HelpTicket


class HelpTicketForm(forms.ModelForm):
    class Meta:
        model = HelpTicket
        fields = ['category', 'city', 'description', 'contact']

findhelp/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

findhelp/helpticket/api/views.py
from rest_framework import viewsets  # , permissions

from findhelp.helpticket.api.serializers import HelpTicketSerializer
from findhelp.helpticket.api.permissions import IsOwnerOrReadOnly
from findhelp.helpticket.models import HelpTicket


class HelpTicketViewSet(viewsets.ModelViewSet):
    queryset = HelpTicket.objects.all()
    serializer_class = HelpTicketSerializer
    permission_classes = [IsOwnerOrReadOnly, ]

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

findhelp/helpticket/views.py
# from django.shortcuts import reverse
# from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

# from itertools import chain
from datetime import timedelta
from django.utils import timezone

from findhelp.helpticket.models import HelpTicket, HelpCategory
from findhelp.users.models import User

PAGINATION = 8


class TicketList(LoginRequiredMixin, ListView):
    paginate_by = PAGINATION
    template_name = 'helpticket/tickets.html'
    context_object_name = 'helptickets'

    def get_context_data(self, **kwargs):
        """
            Add other things to the context
        """
        context = super(TicketList, self).get_context_data(**kwargs)
        context['categories'] = HelpCategory.objects.all()
        return context

    def get_queryset(self):
        time_threshold = timezone.now() - timedelta(days=30)
        helptickets = HelpTicket.objects.filter(updated_at__gt=time_threshold)

        return helptickets


ticket_list_view = TicketList.as_view()


class TicketListCategorized(LoginRequiredMixin, ListView):
    paginate_by = PAGINATION
    template_name = 'helpticket/tickets.html'
    context_object_name = 'helptickets'

    def get_context_data(self, **kwargs):
        """
            Add other things to the context
        """
        context = super(TicketListCategorized, self).get_context_data(**kwargs)
        context['categories'] = HelpCategory.objects.all()
        return context

    def get_queryset(self):
        time_threshold = timezone.now() - timedelta(days=30)
        helptickets = HelpTicket.objects.filter(categories=self.kwargs["pk"], updated_at__gt=time_threshold)

        return helptickets


ticket_list_categorized_view = TicketListCategorized.as_view()


class TicketCreate(LoginRequiredMixin, CreateView):
    model = HelpTicket
    fields = ['categories', 'city', 'description', 'contact']

    def form_valid(self, form):
        form.instance.owner = User.objects.get(username=self.request.user)
        return super(TicketCreate, self).form_valid(form)


ticket_create_view = TicketCreate.as_view(success_url="/")


class TicketUpdate(LoginRequiredMixin, UpdateView):
    model = HelpTicket
    fields = ['categories', 'city', 'description', 'contact']
    success_url = "/"

    def get_object(self, *args, **kwargs):
        obj = super(TicketUpdate, self).get_object(*args, **kwargs)
        if not obj.owner == self.request.user:
            raise PermissionDenied
        return obj


ticket_update_view = TicketUpdate.as_view()


class TicketDelete(LoginRequiredMixin, DeleteView):
    model = HelpTicket
    success_url = "/"

    def get_object(self, *args, **kwargs):
        obj = super(TicketDelete, self).get_object(*args, **kwargs)
        if not obj.owner == self.request.user:
            raise PermissionDenied
        return obj


ticket_delete_view = TicketDelete.as_view()


class ProfileTicketList(LoginRequiredMixin, ListView):
    paginate_by = PAGINATION
    template_name = 'helpticket/profile.html'
    context_object_name = 'helptickets'

    def get_queryset(self):
        helptickets = HelpTicket.objects.filter(owner=self.request.user)

        return helptickets


profile_ticket_list_view = ProfileTicketList.as_view()

findhelp/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

findhelp/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["first_name", "last_name"]

    def get_success_url(self):
        return reverse("helpticket:profile")

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("helpticket:home")


user_redirect_view = UserRedirectView.as_view()

findhelp/templates/base.html
{% load static i18n compress%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Findhelp{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
  <script src="https://use.fontawesome.com/17bdfffc24.js"></script>
  <link rel="icon" href="{% static 'images/logo.png' %}">

  {% block css %}


  <!-- Your stuff: Third-party CSS libraries go here -->
  {% compress css %}
  <!-- This file stores project-specific CSS -->

  <link href="{% static 'css/project.css' %}" rel="stylesheet">

  {% endcompress %}
  {% endblock %}

</head>

<body>

  <div class="mb-1">
    <nav class="navbar navbar-expand-md navbar-light navbar-custom border-bottom">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand" href="{% url 'helpticket:home' %}">
        <img class="" src="{% static 'images/logo.png' %}" width="30" height="30" class="d-inline-block align-top"
          alt="" loading="lazy">
      </a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'landing-home' %}">{% trans 'Home' %}<span
                class="sr-only">(current)</span></a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'civil' %}">{% trans 'Civil Organizations' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'people' %}">{% trans 'Need Help?' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">{% trans 'About' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">{% trans 'Contact' %}</a>
          </li>
        </ul>

        <ul class="navbar-nav mr-auto">
        {% if request.user.is_authenticated %}
        
          <li class="nav-item">
            <a class="nav-link" href="{% url 'helpticket:home' %}"><b>{% trans 'Helptickets' %}</b><span
                class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              {% trans 'Profile' %}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'helpticket:profile'  %}">{% trans 'Edit Helptickets' %}</a>
              <a class="dropdown-item" href="{% url 'users:update'  %}">{% trans 'Update Profile' %}</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'account_logout' %}">{% trans 'Sign Out' %}</a>
            </div>
          </li>
        
          {% endif %}
          {% if not request.user.is_authenticated %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
          </li>
          {% endif %}
        </ul>
        <a class="mr-5">
          <form action="{% url 'set_language' %}" method="post" id="languageform">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}">
          </form>

          <select name="language" onchange="this.form.submit()" form="languageform"
            class="form-control form-control-sm">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
            <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
              {{ language.name_local }}
            </option>
            {% endfor %}
          </select>
        </a>



        <a href="{% url 'helpticket:create-ticket' %}">
          <button type="submit" class="btn btn-outline-primary findhelp my-2 my-sm-0">{% trans 'Find Help' %}</button>
        </a>
      </div>

    </nav>

  </div>

  <div class="container">

    {% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button"
        class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
    {% endfor %}
    {% endif %}

    {% block content %}
    <p>This project is projected to deploy in 10.08.2020. Until then contact yusufhilmicr@gmail.com for more details.
    </p>
    {% endblock content %}


    <footer class="pt-4 my-md-5 pt-md-5 border-top">
      <div class="row">
        <div class="col-4 col-md">
          <img class="mb-2" src="{% static 'images/logo.png' %}" alt="" width="24" height="24">
          <small class="d-block mb-3 text-muted">&copy; Findhelp</small>
        </div>
        <div class="col-4 col-md">
          <h5>{% trans 'About' %}</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="{% url 'civil' %}">{% trans 'Civil Organizations' %}</a></li>
            <li><a class="text-muted" href="{% url 'people' %}">{% trans 'Need Help?' %}</a></li>
            <li><a class="text-muted" href="{% url 'privacy' %}">{% trans 'Privacy Policy' %}</a></li>
            <li><a class="text-muted" href="{% url 'contact' %}">{% trans 'Contact' %}</a></li>
          </ul>
        </div>
        <div class="col-4 col-md">
          <h5>{% trans 'Social' %}</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="https://www.linkedin.com/company/findhelp/">{% trans 'LinkedIn' %}</a></li>
            <li><a class="text-muted" href="https://twitter.com/findhelp__">{% trans 'Twitter' %}</a></li>
            <li><a class="text-muted" href="https://github.com/yusufhilmi/findhelp">{% trans 'GitHub' %}</a></li>
          </ul>
        </div>
      </div>
    </footer>

  </div> <!-- /container -->

  {% block modal %}{% endblock modal %}

  <!-- Le javascript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  {% block javascript %}

  <!-- Vendor dependencies bundled as one file-->
  {% compress js %}
  <script src="{% static 'js/vendors.js' %}"></script>
  {% endcompress %}


  <!-- place project specific Javascript in this file -->
  {% compress js %}
  <script src="{% static 'js/project.js' %}"></script>
  {% endcompress %}

  {% endblock javascript %}
</body>

</html>